name: Test
author: 测试
url: https://ning0ing.github.io
avatar: https://ning-blog-1304206373.cos.ap-nanjing.myqcloud.com/image/something/Avatar.jpg
favicon: https://ning-blog-1304206373.cos.ap-nanjing.myqcloud.com/image/something/favicon.png
